name: release

# runs when a tag v* is pushed
# releases the extension to GitHub and the vscode marketplace

on:
  push:
    tags: ["v*"]

env:
  SCRIPT_DIR: ./.github/scripts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: node $SCRIPT_DIR/enableWebpack.js
      - run: yarn install
      - uses: lannonbr/vsce-action@master
        with:
          args: "package"
      - name: Identify output file # can be retrieved as steps.filenames.outputs.file_out
        id: filenames
        run: echo "::set-output name=file_out::$(ls | grep "^.*\.vsix$" | head -1)"
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.filenames.outputs.file_out }}
          path: ${{ steps.filenames.outputs.file_out }}

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: "artifacts/"
      - name: Get version from tag
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\/v/}
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: "artifacts/*/*"
          prerelease: false
          draft: false


  publish:
    name: Publish
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: node $SCRIPT_DIR/enableWebpack.js
      - run: yarn install
      - uses: lannonbr/vsce-action@master
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
